[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
is-system = true
#stack too deepの解決策
via_ir = true
optimizer = true
optimizer_runs = 200

# [profile.zksync]
# solc = "0.8.25"
# via_ir = true
# optimizer = true
# optimizer_runs = 200
# zk_version = "1.3.19"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
